### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by lampsoft** [AmitXShukla/GPS-Mobile-Tracking-App#1]
Hello, 
Thanks for your script,
I was able to use to createUser and Login User, Update User but I'm getting error 500 for other post and get eg

http://localhost:3000/setlocation
**POST http://localhost:3000/setlocation net::ERR_EMPTY_RESPONSE**

I've been trying to figure it out for past days but it is  not working

HttpErrorResponse {headers: HttpHeaders, status: 500, statusText: "Internal Server Error", url: "http://localhost:3000/setlocation", ok: false, …}
error: "<!DOCTYPE html>↵<html lang="en">↵<head>↵<meta charset="utf-8">↵<title>Error</title>↵</head>↵<body>↵<pre>ReferenceError: userEmail is not defined<br> &nbsp; &nbsp;at C:\Users\Saint Steven\Desktop\NativeScript\GPS-Mobile-Tracking-App\server\app.js:81:5<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\Users\Saint Steven\Desktop\NativeScript\GPS-Mobile-Tracking-App\server\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at next (C:\Users\Saint Steven\Desktop\NativeScript\GPS-Mobile-Tracking-App\server\node_modules\express\lib\router\route.js:137:13)<br> &nbsp; &nbsp;at C:\Users\Saint Steven\Desktop\NativeScript\GPS-Mobile-Tracking-App\server\node_modules\body-parser\lib\read.js:130:5<br> &nbsp; &nbsp;at invokeCallback (C:\Users\Saint Steven\Desktop\NativeScript\GPS-Mobile-Tracking-App\server\node_modules\raw-body\index.js:224:16)<br> &nbsp; &nbsp;at done (C:\Users\Saint Steven\Desktop\NativeScript\GPS-Mobile-Tracking-App\server\node_modules\raw-body\index.js:213:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (C:\Users\Saint Steven\Desktop\NativeScript\GPS-Mobile-Tracking-App\server\node_modules\raw-body\index.js:273:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:188:13)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:1129:12)<br> &nbsp; &nbsp;at process.internalTickCallback (internal/process/next_tick.js:72:19)</pre>↵</body>↵</html>↵"
headers: HttpHeaders {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}
message: "Http failure response for http://localhost:3000/setlocation: 500 Internal Server Error"
name: "HttpErrorResponse"
ok: false
status: 500
statusText: "Internal Server Error"
url: "http://localhost:3000/setlocation"
__proto__: HttpResponseBase

**Comment by AmitXShukla** [comment]
I will check this code and get back to you. I can see why it might be happening, if Client is not sending userEmail (which is not needed in case of setLocation anyway), and server app.js  (line 81) is complaining about. Try commenting any reference user Email in app.js (line 81) and see if error goes away.
I will test and update this code later today.
